Update rds_regex in AWS log forwarder to correctly support serverless clusters
DataDog/datadog-serverless-functions pull request #186
Opened 2019-12-27 15:36 UTC by vitorog

### What does this PR do?

Modifies the rds_regex to properly match the log group names for RDS aurora serverless clusters.
For serverless clusters, the log groups are named as:
/aws/rds/cluster/<cluster_name>/postgresql

And for RDS instances, they are named as:
/aws/rds/instance/<instance_name>/postgresql

### Motivation

After creating some aurora serverless clusters, I noticed that
the "host" property was missing in datadog logs.

### Additional Notes

Not sure if this is the best fix for this issue, but updating the regex seems to have fixed it.

2019-12-30 21:52 UTC, sfirrin commented
Thanks for this PR @vitorog, I'm going to bump the forwarder version and merge it.

2019-12-30 22:07 UTC, swfunc requested changes
@vitorog I realized I can't push to your forked branch, if you bump the version by changing line 258 to

```
DD_FORWARDER_VERSION = "2.3.4"
```

then I can merge the branch as-is.

2019-12-30 22:19 UTC, vitorog commented
Hi, @sfirrin , thanks!
I bumped the version as requested.

2019-12-31 15:07 UTC, swfunc approved these changes
Thanks @vitorog

2019-12-31 15:07 UTC, merged